### ISSUE TITLE
Timed Key token validation fails to authenticate when ClientID does not match case

### ISSUE THREAD

**Issue by LeBecca** [csgsolutions/aspnetcore-apikeys#2]
Timed Key token validation fails to authenticate when ClientID does not match case between request auth token and the ClientID returned from GetKeyAsync

**Comment by jusbuc2k** [comment]
I'm not able to reproduce this issue. I did create unit tests to cover these scenarios with the built-in key store providers.

https://github.com/csgsolutions/aspnetcore-apikeys/blob/a0c05aa49ebb6475df1376e04ff7310c2487b284/tests/Csg.AspNetCore.Authentication.ApiKey.Tests/ApiKeyHandlerTests.cs#L134
